<html>
<head>
    <meta charset="utf-8" />
    <title>Chamados</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/CSS/Index.css">
</head>

<body>
<div class="container">
    <div class="container-content">
        <form action="/auth" method="POST">

            <div class="logo">
                <img src="" alt="Logo">
            </div>

            <div class="input-content">
                <div class="input-section">
                    <input type="text" placeholder="usuario" id="user" name="username" class="input">
                    <label for="user" class="input-label">Usuário</label>
                </div>
                <div class="input-section">
                    <input type="password" placeholder="senha" id="password" name="password" class="input">
                    <label for="password" class="input-label">Senha</label>
                </div>
            </div>

            <?php if ($this->view->login == 'error') { ?>

                <span class="text-danger"> Login ou senha inválido(s)</span>

            <?php } ?>

            <button type="submit" class="btn-submit">Login</button>
        </form>
    </div>
</div>
</body>
</html>
