<script>
    var Atual = document.getElementById('cardapio');
    Atual.setAttribute('class','point')
</script>

<!-- <section>

</section>

<section class="produtos">
    <details>
        <summary>Sumário 1</summary>
        <ul>
            <li>1</li>
            <li>1</li>
            <li>1</li>
            <li>1</li>
            <li>1</li>
            <li>1</li>
        </ul>
    </details>
</section> -->

<?php

echo '<pre>';
print_r($this->view->produtos);